# -*- coding: utf-8 -*-
"""
Created on Sat Dec 14 08:13:30 2019

@author: carso
"""

partnership_topics = '''
#### Partnership Tax Topics
###### Check the box
* Per se corporations
* Default and elective status for foreign and U.S. entities
'''

basic_topics = '''
            #### Basic Tax Topics            
            ###### Rates
            * Marginal tax rates given taxable income for:
                * Married filing jointly
                * Single
                * Head of household
            ###### Unrestricted Property as Compensation
            ###### Restricted Property as Compensation
            * With and without Section 83(b) election
            * With and without forfeiture
            ###### Options as Compensation
            * Unrestricted options only
            * With and without readily ascertainable fair market value
            * No ISOs
            ###### Different Ways of Satisfying a Debt
            * Cancellation of indebtedness
            * Property
            * Services
            ###### Bonds, Shifting Interest Rates, and COD
            * Debt sold back to borrower v. debt sold to third party
            * Finding present value of bond due to change in interest rates
            ###### Gain from Sale of Principal Residence
            * Married filing jointly and single
            * Satisfies two-year residence requirement v. does not satisfy requirement
            * Sometimes relaxation of two-year residence requirement applies (Section 121(c) exception)
            ###### COD Exclusion
            * Insolvency exception
            ###### Home Mortgage Interest Deduction
            * Married filing jointly and single
            ###### Basis
            * Basis step-up at death
            * Gift basis
            * Part gift/part sale
            * Part donation/part sale
            * Transfers between spouses or incident to divorce
            ###### Transactions with Liabilities
            * Disposition of encumbered property
            * Recourse v. nonrecourse
            * Debt sometimes in excess of fair market value
            ###### Like-Kind Exchanges
            * With non-cash boot
            * With and without net debt relief
            * With and without both sides' qualifying for like-kind treatment
            ###### Installment Sales
            * Plain installment sales
            * Debt relief as compensation, with and without debt as qualifying debt
            * Related party resale (section 453(e)), with and without first buyer as actual related party
            * Installment sale with like-kind exchange
            ###### Depreciation
            * With and without sale of property
            ###### Capital gain netting
            * Calculating net capital gain
            * Capital loss carryovers
            ###### Section 1231 netting
            * Determining how much ordinary income is generated by the sale of assets used for business. Assumes away depreciation (recapture) and the presence of capital assets.
            ###### Recapture
            * Amount and character of recapture with sale of a single asset. Requires calculating depreciation.
            ###### Section 24 credit
            * qualifying child, qualifying relative, phaseout
            ###### Section 21 credit
            * with and without phaseout
            * with and without qualifying individual
            * with and without DCAP contribution
            '''