# -*- coding: utf-8 -*-
"""
Created on Sat Feb  1 19:02:25 2020

@author: Lawsky
"""
import math

class StatuteExcerpt:
    def __init__(self,lang_to_eval,input_dict,func_to_eval,power_of_ten,ask_lang):
        self.lang_to_eval = lang_to_eval
        self.input_dict = input_dict
        self.func_to_eval = func_to_eval
        self.power_of_ten = power_of_ten
        self.ask_lang = ask_lang
        

class SeedValues:
    def __init__(self,seed_amount,seed_start,seed_end,seed_type):
        self.seed_amount = seed_amount
        self.seed_start = seed_start
        self.seed_end = seed_end
        self.seed_type = seed_type

section_1 = StatuteExcerpt('10 percent of the lesser of the amount described in paragraph (4)(A)(ii)(I) or the excess of the gross income of such child over the amount so described',{'amount described in paragraph (4)(A)(ii)(I)':'default','gross income of such child':SeedValues('previous',80,120,'curr')},lambda a,b:.1*min(a,max(0,b-a)),3,'default')

section_21 = StatuteExcerpt("(a)(1) In the case of an individual for which there are 1 or more qualifying individuals (as defined in subsection (b)(1)) with respect to such individual, there shall be allowed as a credit against the tax imposed by this chapter for the taxable year an amount equal to the applicable percentage of the employment-related expenses (as defined in subsection (b)(2)) paid by such individual during the taxable year. (2) For purposes of paragraph (1), the term 'applicable percentage' means 35 percent reduced (but not below 20 percent) by 1 percentage point for each $2,000 (or fraction thereof) by which the taxpayer's adjusted gross income for the taxable year exceeds $15,000....(c) The amount of the employment-related expenses incurred during any taxable year which may be taken into account under subsection (a) shall not exceed $3000",{'amount of employment-related expenses incurred during the taxable year':SeedValues(3000,80,120,'curr'),'adjusted gross income':SeedValues(37000,80,120,'curr')},lambda a,b:min(a,3000)*(35-min(15,math.ceil((b-15000)/2000)))/100,2,'the credit allowable')

section_22 = StatuteExcerpt('the section 22 amount shall be reduced by one-half of the excess of the adjusted gross income over $7,500',{'section 22 amount':'default','adjusted gross income':SeedValues('previous',80,120,'curr')},lambda a,b:a-((1/2)*max(b-7500,0)),3,'the reduced section 22 amount')

section_24 = StatuteExcerpt("(a) There shall be allowed as a credit against the tax imposed by this chapter for the taxable year with respect to each qualifying child of the taxpayer for which the taxpayer is allowed a deduction under section 151 an amount equal to $1,000. (b)(1) The amount of the credit allowable under subsection (a) shall be reduced (but not below zero) by $50 for each $1,000 (or fraction thereof) by which the taxpayer's modified adjusted gross income exceeds the threshold amount....(2) For purposes of paragraph (1), the term 'threshold amount' means $110,000",{'modified adjusted gross income':SeedValues(120000,90,110,'curr')},lambda a:min(1000,max(0,1000-50*(math.ceil((a-110000)/1000)))),2,'the credit allowed')

section_25 = StatuteExcerpt("the term 'excess credit amount' means the excess of (I) the credit amount for any mortgage credit certificate program, over (II) the amount which would have been the credit amount for such program had such program met the requirements of paragraph (2) of subsection (d)",{"credit amount for any mortgage credit certificate program":'default',"amount which would have been the credit amount for such program had such program met the requirements of paragraph (2) of subsection (d)":SeedValues('previous',80,120,'curr')},lambda a,b:max(0,a-b),3,'the excess credit amount')

section_25A = StatuteExcerpt("The American Opportunity Tax Credit (determined without regard to this paragraph) shall be reduced (but not below zero) by the amount which bears the same ratio to such credit (as so determined) as (A) the excess of (i) the taxpayer's modified adjusted gross income for such taxable year, over (ii) $80,000...bears to (B) $10,000",{'American Opportunity Tax Credit':SeedValues(2000,80,120,'curr'),'modified adjusted gross income':SeedValues(85000,80,120,'curr')},lambda a,b:max(0,a-a*(max(0,b-80000)/10000)),2,'the American Opportunity Tax Credit after reduction')

section_30B_d = StatuteExcerpt("the qualified incremental hybrid cost of any vehicle is equal to the amount of the excess of the manufacturer's suggested retail price for such vehicle over such price for a comparable vehicle, to the extent such amount does not exceed...$7,500",{"manufacturer's suggested retail price for the vehicle":SeedValues(32000,90,120,'curr'),'price for a comparable vehicle':SeedValues(30000,80,120,'curr')},lambda a,b:min(7500,max(0,a-b)),2,'the qualified incremental hybrid cost of the vehicle')

section_30B_e = StatuteExcerpt("the incremental cost of any new qualified alternative fuel motor vehicle is equal to the amount of the excess of the manufacturer's suggested retail price for such vehicle over such price for a gasoline or diesel fuel motor vehicle of the same model, to the extent such amount does not exceed...$10,000",{"manufacturer's suggested retail price for the vehicle":SeedValues(34000,80,120,'curr'),"price for a gasoline or diesel fuel motor vehicle of the same model":SeedValues(30000,80,120,'curr')},lambda a,b:min(10000,max(0,a-b)),2,'the incremental cost of the new qualified alternative fuel motor vehicle')

section_36 = StatuteExcerpt("the tax imposed by this chapter for the taxable year of such disposition or cessation shall be increased by the excess of the amount of the credit allowed over the amounts of tax imposed by paragraph (1) for preceding taxable years",{"amount of the credit allowed":SeedValues(8000,80,120,'curr'),"amounts of tax imposed by paragraph (1) for preceding taxable years":SeedValues('previous',80,120,'curr')},lambda a,b:max(0,a-b),2,'the amount by which the tax imposed by this chapter shall be increased')

section_41_a = StatuteExcerpt("20 percent of the excess (if any) of (A) the qualified research expenses for the taxable year, over (B) the base amount",{"amount of the qualified research expenses for the taxable year":SeedValues(10000,80,120,'curr'),"base amount":SeedValues('previous',80,120,'curr')},lambda a,b:.2*max(0,a-b),2,'default')

section_42_d = StatuteExcerpt("The excess described in this clause with respect to any unit is the excess of (I) the cost of such unit, over (II) the amount which would be the cost of such unit if the average cost per square foot of low-income units in the building were substituted for the cost per square foot of such unit",{'cost of the unit':SeedValues(50000,80,120,'curr'),"amount which would be the cost of such unit if the average cost per square foot of low-income units in the building were substituted for the cost per square foot of such unit":SeedValues('previous',70,99,'curr')},lambda a,b:max(0,a-b),3,'the excess described in this clause with respect to the unit')

section_45K = StatuteExcerpt("The amount allowable as a credit under subsection (a) with respect to any project for any taxable year (determined after the application of paragraphs (1), (2), and (3)) shall be reduced by the excess of (A) the aggregate amount allowed under section 38 for the taxable year or any prior taxable year by reason of the energy percentage with respect to property used in the project, over (B) the aggregate amount recaptured with respect to the amount described in subparagraph (A)",{"aggregate amount allowed under section 38 for the taxable year or any prior taxable year by reason of the energy percentage with respect to property used in the project":SeedValues(15000,80,120,'curr'),"aggregate amount recaptured with respect to the amount described in subparagraph (A)":SeedValues('previous',80,120,'curr')},lambda a,b:max(0,a-b),2,'the amount by which the allowable credit shall be reduced')

section_58 = StatuteExcerpt("For purposes of this paragraph, the term 'insolvent' means the excess of liabilities over the fair market value of assets",{"amount of the liabilities":'default',"fair market value of the assets":SeedValues('previous',80,120,'curr')},lambda a,b:max(0,a-b),3,'the extent to which the taxpayer is insolvent')

section_68 = StatuteExcerpt("In the case of an individual whose adjusted gross income exceeds the applicable amount, the amount of the itemized deductions otherwise allowable for the taxable year shall be reduced by the lesser of (1) 3 percent of the excess of adjusted gross income over the applicable amount, or (2) 80 percent of the amount of the itemized deductions otherwise allowable for such taxable year",{"adjusted gross income":SeedValues(400000,80,120,'curr'),"amount of the itemized deductions otherwise allowable for such taxable year":SeedValues(3000,80,120,'curr')},lambda a,b:b-min(.03*max(0,a-300000),.8*b),2,"the amount of itemized deductions after the described reduction, assuming that the 'applicable amount' is $300,000")

section_72 = StatuteExcerpt("If an individual who holds an annuity contract transfers it without full and adequate consideration, such individual shall be treated as receiving an amount equal to the excess of (I) the cash surrender value of such contract at the time of transfer, over (II) the investment in such contract at such time",{'cash surrender value of the contract at the time of transfer':'default','investment in the contract at such time':SeedValues('previous',80,120,'curr')},lambda a,b:max(0,a-b),3,'the amount that the invididual is treated as receiving')

section_79 = StatuteExcerpt("There shall be included in the gross income of an employee for the taxable year an amount equal to the cost of group-term life insurance on his life provided for part or all of such year under a policy (or policies) carried directly or indirectly by his employer (or employers); but only to the extent that such cost exceeds the sum of (1) the cost of $50,000 of such insurance, and (2) the amount (if any) paid by the employee toward the purchase of such insurance",{"cost of group-term life insurance on the employee's life provided for part or all of such year under a policy (or policies) carried directly or indirectly by his employer":SeedValues(10000,80,140,'curr'),'cost of $50,000 of such insurance':SeedValues(3000,60,120,'curr'),'amount paid by the employee toward the purchase of the insurance':SeedValues(5000,60,120,'curr')},lambda a,b,c:max(0,a-(b+c)),2,"the amount included in the employee's gross income due to this provision")

section_119 = StatuteExcerpt("Paragraph (1) shall not apply to the extent of the excess of (A) the lesser of (i) 5 percent of the appraised value of the qualified campus lodging, or (ii) the average of the rentals paid by individuals (other than employees or students of the educational institution) during such calendar year for lodging provided by the educational institution which is comparable to the qualified campus lodging provided to the employee, over (B) the rent paid by the employee for the qualified campus lodging during such calendar year",{'appraised value of the qualified campus lodging':SeedValues(200000,80,120,'curr'),'average of the rentals paid by individuals (other than employees or students of the educational institution) during such calendar year for lodging provided by the educational institution which is comparable to the qualified campus lodging provided to the employee':SeedValues(12000,80,120,'curr'),'rent paid by the employee for the qualified campus lodging during such calendar year':SeedValues(10000,80,110,'curr')},lambda a,b,c:max(0,min((.05*a),b)-c),2,'the extent to which Paragraph (1) shall not apply')

section_132 = StatuteExcerpt("The term 'gross profit percentage' means the percent which (i) the excess of the aggregate sales price of property sold by the employer to customers over the aggregate cost of such property to the employer, is of (ii) the aggregate sale price of such property",{"aggregate sales price of property sold by the employer to customers":SeedValues(100000,80,120,'curr'),'aggregate cost of such property to the employer':SeedValues(60000,80,120,'curr')},lambda a,b:int(100*(a-b)/a),3,'the gross profit percentage')

section_139B = StatuteExcerpt("expenses paid or incurred by the taxpayer in connection with the performance of services as such a member shall be taken into account under section 170 only to the extent such expenses exceed the amount of any qualified payment excluded from gross income under subsection (a)",{"expenses paid or incurred by the taxpayer in connection with the performance of services as such a member":SeedValues(6000,80,120,'curr'),"amount of qualified payment excluded from gross income under subsection (a)":SeedValues(5000,80,120,'curr')},lambda a,b:max(0,a-b),2,'the amount of expenses taken into account under Section 170')

section_162_r = StatuteExcerpt("the term 'applicable percentage' means, with respect to any taxpayer for any taxable year, the ratio (expressed as a percentage but not greater than 100 percent) which (A) the excess of (i) the total consolidated assets of such taxpayer (determined as of the close of such taxable year), over (ii) $10,000,000,000, bears to (B) $40,000,000,000",{'total consolidated assets of the taxpayer':SeedValues(41*(10**9),80,120,'curr')},lambda a:100*min(1,(a-10000000000)/40000000000),9,'the applicable percentage')

section_32 = StatuteExcerpt("The amount of the credit allowable to a taxpayer under paragraph (1) for any taxable year shall not exceed the excess (if any) of (A) the credit percentage of the earned income amount, over (B) the phaseout percentage of so much of the adjusted gross income (or, if greater, the earned income) of the taxpayer for the taxable year as exceeds the phaseout amount",{"taxpayer's adjusted gross income":SeedValues(20000,80,120,'curr'),"taxpayer's earned income":SeedValues(20000,80,120,'curr')},lambda a,b:max(0,(.34*10000-max(0,.1598*max(0,(max(a,b)-19500))))),2,"the amount that the credit allowable shall not exceed, assuming that the earned income amount is $10,000, the credit percentage is 34%, the phaseout amount is $19,500, and the phaseout percentage is 15.98%")

section_45 = StatuteExcerpt('The amount of the credit determined under subsection (a) shall be reduced by an amount which bears the same ratio to the amount of the credit (determined without regard to this paragraph) as (A) the amount by which the reference price for the calendar year in which the sale occurs exceeds 8 cents, bears to (B) 3 cents',{'reference price':SeedValues(8.5,80,150,'cents')},lambda a:max(0,100-(100*max(0,a-8)/3)),-2,'the credit after the reduction, assuming that the credit before the reduction was $100')

section_151 = StatuteExcerpt("(A) In the case of any taxpayer whose adjusted gross income for the taxable year exceeds the applicable amount in effect under section 68(b), the exemption amount shall be reduced by the applicable percentage. (B) For purposes of subparagraph (A), the term 'applicable percentage' means 2 percentage points for each $2,500 (or fraction thereof) by which the taxpayer's adjusted gross income for the taxable year exceeds the applicable amount in effect under section 68(b)....In no event shall the applicable percentage exceed 100 percent",{'adjusted gross income':SeedValues(260000,80,120,'curr')},lambda a:2500*(100-min(100,2*max(0,(math.ceil(a/2500)-100))))/100,2,"the exemption amount after reduction, assuming that the exemption amount before reduction is $2,500 and the applicable amount is $250,000")

section_163 = StatuteExcerpt("(i) Premiums paid or accrued for qualified mortgage insurance by a taxpayer during the taxable year in connection with acquisition indebtedness with respect to a qualified residence of the taxpayer shall be treated for purposes of this section as interest which is qualified residence interest. (ii) The amount otherwise treated as interest under clause (i) shall be reduced (but not below zero) by 10 percent of such amount for each $1,000...(or fraction thereof) that the taxpayer's adjusted gross income for the taxable year exceeds $100,000",{"amount of premiums paid or accrued for qualified mortgage insurance by a taxpayer during the taxable year in connection with acquisition indebtedness with respect to a qualified residence of the taxpayer":SeedValues(5000,80,120,'curr'),"adjusted gross income":SeedValues(102000,80,120,'curr')},lambda a,b:round(a*max(0,1-.1*(math.ceil(max(0,b-100000)/1000))),1),2,"the amount of the premiums after the reduction")

section_409 = StatuteExcerpt("The plan provides that, unless the participant elects otherwise, the distribution of the participant's account balance will be in substantially equal periodic payments (not less frequently than annually) over a period not longer than the greater of (i) 5 years, or (ii) in the case of a participant with an account balance in excess of $800,000, 5 years plus 1 additional year (but not more than 5 additional years) for each $160,000 or fraction thereof by which such balance exceeds $800,000",{"account balance":SeedValues(820000,90,200,'curr')},lambda a:5+min(5,(math.ceil(max(0,a-800000)/160000))),2,"the longest period over which the account balance will be distributed")

section_2031 = StatuteExcerpt("(i) The benefit requirements of this subparagraph are met with respect to the defined benefit plan forming part of the eligible combined plan if the accrued benefit of each participant derived from employer contributions, when expressed as an annual retirement benefit, is not less than the applicable percentage of the participant's final average pay.... (ii) For purposes of clause (i), the applicable percentage is the lesser of (I) 1 percent multiplied by the number of years of service with the employer, or (II) 20 percent",{"employee's number of years of service with the employer":SeedValues(16,70,110,'nocurr'),"participant's final average pay":'default'},lambda a,b:b*min(a,20)/100,0,"the amount that equals the applicable percentage of the participant's final average pay")

section_6651_a1 = StatuteExcerpt("In case of failure to file any return required under authority of subchapter A of chapter 61 (other than part III thereof), subchapter A of chapter 51 (relating to distilled spirits, wines, and beer), or of subchapter A of chapter 52 (relating to tobacco, cigars, cigarettes, and cigarette papers and tubes), or of subchapter A of chapter 53 (relating to machine guns and certain other firearms), on the date prescribed therefor (determined with regard to any extension of time for filing), unless it is shown that such failure is due to reasonable cause and not due to willful neglect, there shall be added to the amount required to be shown as tax on such return 5 percent of the amount of such tax if the failure is for not more than 1 month, with an additional 5 percent for each additional month or fraction thereof during which such failure continues, not exceeding 25 percent in the aggregate",{'tax shown on the return':'default','number of months during which the failure to file continued':SeedValues(4,80,140,'nocurr')}, lambda a,b:a*(1+min(25,5*math.ceil(b))/100),-2,'the tax shown on the return after the increase required')

section_6651_a2 = StatuteExcerpt("In case of failure to...pay the amount shown as tax on any return specified in paragraph (1) on or before the date prescribed for payment of such tax (determined with regard to any extension of time for payment), unless it is shown that such failure is due to reasonable cause and not due to willful neglect, there shall be added to the amount shown as tax on such return 0.5 percent of the amount of such tax if the failure is for not more than 1 month, with an additional 0.5 percent for each additional month or fraction thereof during which such failure continues, not exceeding 25 percent in the aggregate",{'tax shown on the return':'default','number of months during which the failure to pay tax continued':SeedValues(15,30,200,'nocurr')},lambda a,b:a*(1+min(25,.5*math.ceil(b))/100),-2,'the tax shown on the return after the increase required')


test_object = section_1

full_list = [section_1,section_21,section_22,section_24,section_25,section_25A,section_30B_d,section_30B_e,section_32,section_36,section_41_a,section_42_d,section_45,section_45K,section_58,section_68,section_72,section_79,section_119,section_132,section_151,section_162_r,section_163,section_409,section_2031,section_6651_a1,section_6651_a2]

#print(len(full_list))